const QUESTION_BANK = [
  { id: "a6-01", mainNumber: 1, priority: 5, source: "Aula 6", topic: "Fundamentos da POO", prompt: "Segundo o material da Aula 6, qual é a ideia central da Programação Orientada a Objetos?", options: ["Organizar o software em torno de objetos que unem dados e comportamentos.", "Escrever apenas funções soltas que manipulam variáveis globais.", "Evitar classes e trabalhar somente com comandos print().", "Separar completamente dados e operações em arquivos diferentes.", "Usar somente herança em todos os programas."], answer: 0, explanation: "POO organiza o sistema em objetos, que possuem atributos e métodos relacionados." },
  { id: "a6-02", mainNumber: 2, priority: 5, source: "Aula 6", topic: "Classes e Objetos", prompt: "Qual alternativa diferencia corretamente classe e objeto?", options: ["Classe é o molde; objeto é uma instância concreta criada a partir desse molde.", "Classe é sempre uma variável; objeto é sempre uma função.", "Classe só existe em diagrama; objeto só existe em banco de dados.", "Objeto é o molde; classe é o valor digitado pelo usuário.", "Classe e objeto são exatamente a mesma coisa."], answer: 0, explanation: "O PDF define classe como modelo/molde e objeto como algo criado a partir dele." },
  { id: "a6-03", mainNumber: 3, priority: 5, source: "Aula 6", topic: "Abstração", prompt: "O que é abstração em POO?", options: ["Representar somente os aspectos essenciais para o contexto do sistema.", "Copiar todas as características reais de uma entidade.", "Criar muitas subclasses sem necessidade.", "Transformar todo método em atributo.", "Impedir que objetos tenham comportamentos."], answer: 0, explanation: "Abstração reduz a complexidade escolhendo o que importa para o problema." },
  { id: "a6-04", mainNumber: 4, priority: 5, source: "Aula 6", topic: "Encapsulamento", prompt: "Encapsulamento está relacionado principalmente a qual ideia?", options: ["Organizar estado e comportamento dentro da classe e controlar o acesso ao estado interno.", "Criar uma classe para cada linha de código.", "Evitar o uso de métodos.", "Transformar atributos em comentários.", "Executar o programa sem objetos."], answer: 0, explanation: "Encapsular é proteger e organizar dados e comportamentos dentro de uma unidade." },
  { id: "a6-05", mainNumber: 5, priority: 5, source: "Aula 6", topic: "Regras de negócio", prompt: "Por que alterar diretamente o atributo saldo de uma conta pode ser perigoso?", options: ["Porque pode permitir valores inválidos e ignorar regras como depósito, saque e saldo suficiente.", "Porque Python não permite atributos numéricos.", "Porque todo saldo precisa ser texto.", "Porque métodos não podem modificar atributos.", "Porque objetos não podem representar conta bancária."], answer: 0, explanation: "O material mostra que o saldo deve ser alterado por métodos que validam as regras." },
  { id: "a6-06", mainNumber: 6, priority: 5, source: "Aula 6", topic: "Herança", prompt: "O que a herança permite fazer?", options: ["Criar uma classe baseada em outra, reutilizando características e comportamentos.", "Apagar todos os métodos da classe principal.", "Evitar qualquer relação entre classes.", "Criar objetos sem classe.", "Impedir o polimorfismo."], answer: 0, explanation: "Herança cria subclasses a partir de uma superclasse, reaproveitando elementos comuns." },
  { id: "a6-07", mainNumber: 7, priority: 5, source: "Aula 6", topic: "Polimorfismo", prompt: "Qual definição representa polimorfismo?", options: ["Diferentes objetos usados por uma mesma operação, com comportamentos específicos.", "Uma classe sem atributos.", "Um método que nunca muda.", "Um atributo privado obrigatório.", "Uma função que só imprime texto."], answer: 0, explanation: "Polimorfismo permite que a mesma chamada produza comportamentos diferentes." },
  { id: "a6-08", mainNumber: 8, priority: 5, source: "Aula 6", topic: "Extensibilidade", prompt: "No exemplo de pagamentos, por que o polimorfismo melhora a extensibilidade?", options: ["Porque novas formas de pagamento podem ser adicionadas sem alterar necessariamente o processamento principal.", "Porque todos os pagamentos passam a usar o mesmo banco de dados.", "Porque impede criar novas classes.", "Porque elimina a necessidade de métodos.", "Porque obriga o uso de variáveis globais."], answer: 0, explanation: "O código principal chama processar(), enquanto cada forma de pagamento implementa seu comportamento." },
  { id: "a6-09", mainNumber: 9, priority: 5, source: "Aula 6", topic: "Sobrecarga e Sobrescrita", prompt: "Qual alternativa descreve sobrescrita (overriding)?", options: ["Uma subclasse redefine um método herdado da classe principal.", "Dois métodos têm nomes diferentes e fazem coisas iguais.", "Um atributo recebe um valor negativo.", "Uma classe deixa de ter construtor.", "Um objeto é criado sem memória."], answer: 0, explanation: "Sobrescrita acontece quando a classe filha especializa um método herdado." },
  { id: "a6-10", mainNumber: 10, priority: 5, source: "Aula 6", topic: "Composição e Agregação", prompt: "Qual relação descreve melhor composição?", options: ["Um objeto composto controla ou contém partes que fazem sentido dentro dele.", "Uma subclasse sempre substitui a classe principal.", "Um objeto existe apenas como texto.", "Um método chama print() várias vezes.", "Uma classe nunca possui atributos."], answer: 0, explanation: "No PDF, Pedido formado por ItemPedido exemplifica composição." },
  { id: "a6-11", mainNumber: 11, priority: 5, source: "Aula 6", topic: "Classes em Python", prompt: "Em Python, para que serve o método __init__()?", options: ["Inicializar/preparar o objeto quando ele é criado.", "Apagar uma classe depois da execução.", "Imprimir automaticamente todos os atributos.", "Criar um arquivo PDF.", "Substituir a palavra class."], answer: 0, explanation: "__init__() prepara a instância e normalmente recebe os valores iniciais." },
  { id: "a6-12", mainNumber: 12, priority: 5, source: "Aula 6", topic: "Encapsulamento em Python", prompt: "Como o encapsulamento em Python funciona principalmente?", options: ["Por convenções, propriedades e design da classe, mais do que por bloqueios rígidos.", "Por proibição total de atributos públicos.", "Somente com herança múltipla.", "Somente com print().", "Python não possui nenhuma forma de encapsulamento."], answer: 0, explanation: "O material cita atributos públicos, _protegidos por convenção e __name mangling." },
  { id: "a6-13", mainNumber: 13, priority: 5, source: "Aula 6", topic: "Herança em Python", prompt: "Qual é o papel de super().__init__() em uma subclasse?", options: ["Chamar o construtor da classe principal para reutilizar a inicialização comum.", "Criar uma variável global chamada super.", "Impedir que a subclasse tenha atributos próprios.", "Apagar o objeto após sua criação.", "Transformar método em comentário."], answer: 0, explanation: "super().__init__() reaproveita a inicialização da classe-pai." },
  { id: "a6-14", mainNumber: 14, priority: 5, source: "Aula 6", topic: "Duck typing", prompt: "O que significa duck typing em Python?", options: ["Se o objeto possui o comportamento necessário, ele pode ser usado, mesmo sem hierarquia formal.", "Todo objeto precisa herdar obrigatoriamente de Animal.", "O tipo do objeto é mais importante que seus métodos.", "Somente classes abstratas podem ser usadas.", "Objetos não podem compartilhar nomes de métodos."], answer: 0, explanation: "Python foca no comportamento disponível no objeto." },
  { id: "a6-15", mainNumber: 15, priority: 5, source: "Aula 6", topic: "Dunder methods", prompt: "O que são métodos especiais, como __str__() e __len__()?", options: ["Métodos com dois sublinhados que integram objetos personalizados às operações da linguagem.", "Métodos que só funcionam em PDFs.", "Atributos sem valor.", "Comentários obrigatórios em classes.", "Métodos que impedem instanciar objetos."], answer: 0, explanation: "Dunder methods permitem usar recursos como len(objeto), == e representações em texto." },
  { id: "a6-16", mainNumber: 16, priority: 5, source: "Aula 6", topic: "Classes abstratas", prompt: "Para que serve uma classe abstrata?", options: ["Definir um modelo/contrato que subclasses devem implementar.", "Executar sempre sem subclasses.", "Guardar apenas imagens.", "Substituir todos os atributos por listas.", "Impedir qualquer forma de polimorfismo."], answer: 0, explanation: "Com abc, uma classe abstrata estabelece comportamentos obrigatórios para filhas." },
  { id: "a6-17", mainNumber: 17, priority: 5, source: "Aula 6", topic: "Múltipla herança", prompt: "Qual risco aparece no uso de múltipla herança?", options: ["Aumentar a complexidade e gerar conflitos de métodos, como no problema do diamante.", "Impedir o uso de classes.", "Eliminar automaticamente todos os métodos.", "Tornar impossível usar Python.", "Fazer todo atributo virar público."], answer: 0, explanation: "O material alerta para conflitos e complexidade em múltipla herança." },
  { id: "a6-18", mainNumber: 18, priority: 5, source: "Aula 6", topic: "Property", prompt: "Qual é uma utilidade de property em Python?", options: ["Permitir acesso simples a um atributo mantendo validações e regras.", "Criar uma nova linguagem.", "Impedir qualquer alteração de objeto.", "Executar somente códigos de banco.", "Substituir todos os métodos da classe."], answer: 0, explanation: "@property ajuda a controlar leitura e alteração de atributos." },
  { id: "a6-19", mainNumber: 19, priority: 5, source: "Aula 6", topic: "Composição em Python", prompt: "No exemplo de comércio eletrônico, por que Pedido e ItemPedido são composição e não herança?", options: ["Porque um pedido é formado por itens; ItemPedido não é um tipo de Pedido.", "Porque todo pedido deve herdar de Produto.", "Porque Cliente é subclasse de ItemPedido.", "Porque composição não usa objetos.", "Porque herança e composição são idênticas."], answer: 0, explanation: "A relação correta é 'possui/é formado por', não 'é um'." },
  { id: "a6-20", mainNumber: 20, priority: 5, source: "Aula 6", topic: "Strategy", prompt: "Qual é a ideia do padrão Strategy?", options: ["Encapsular diferentes algoritmos atrás de uma interface comum.", "Criar muitas condições if sem necessidade.", "Guardar todos os dados em uma única classe.", "Impedir troca de comportamento.", "Usar herança para qualquer relação."], answer: 0, explanation: "Strategy permite trocar estratégias sem o contexto conhecer detalhes." },
  { id: "a6-21", mainNumber: 21, priority: 5, source: "Aula 6", topic: "SRP", prompt: "O que diz o Princípio da Responsabilidade Única (SRP)?", options: ["Uma classe deve ter uma responsabilidade bem definida e um motivo coerente para mudar.", "Uma classe deve possuir apenas um método sempre.", "Uma classe deve enviar e-mail, salvar banco e calcular desconto ao mesmo tempo.", "Toda classe precisa herdar de outra.", "Toda função deve ser global."], answer: 0, explanation: "SRP separa responsabilidades distintas para melhorar manutenção." },
  { id: "a6-22", mainNumber: 22, priority: 5, source: "Aula 6", topic: "OCP", prompt: "O que significa o Princípio Aberto/Fechado (OCP)?", options: ["Aberto para extensão e fechado para modificações constantes no código existente.", "Aberto para editar tudo sempre.", "Fechado para novas funcionalidades.", "Aberto apenas para atributos públicos.", "Fechado para o uso de classes."], answer: 0, explanation: "OCP busca adicionar comportamentos sem alterar repetidamente o código principal." },
  { id: "a6-23", mainNumber: 23, priority: 5, source: "Aula 6", topic: "Acoplamento e Coesão", prompt: "Qual combinação é desejável em uma arquitetura?", options: ["Baixo acoplamento e alta coesão.", "Alto acoplamento e baixa coesão.", "Nenhuma classe com responsabilidade.", "Todas as classes dependendo diretamente umas das outras.", "Somente uma classe para todo o sistema."], answer: 0, explanation: "Baixo acoplamento reduz impactos; alta coesão mantém responsabilidades relacionadas." },
  { id: "a6-24", mainNumber: 24, priority: 5, source: "Aula 6", topic: "Interface e Implementação", prompt: "Por que separar interface e implementação?", options: ["Para usar uma classe sem conhecer seus detalhes internos e facilitar substituições.", "Para impedir manutenção.", "Para transformar código em imagem.", "Para evitar métodos públicos.", "Para obrigar dependência direta de banco específico."], answer: 0, explanation: "A separação permite trocar detalhes internos sem afetar consumidores." },
  { id: "a6-25", mainNumber: 25, priority: 5, source: "Aula 6", topic: "DIP", prompt: "O que o Princípio da Inversão de Dependência recomenda?", options: ["Classes importantes devem depender de abstrações, não de implementações específicas.", "A classe Pedido deve depender diretamente de MySQL.", "Todo sistema deve evitar interfaces.", "Toda subclasse deve apagar a superclasse.", "Métodos não devem receber parâmetros."], answer: 0, explanation: "DIP reduz acoplamento ao depender de contratos/abstrações." },
  { id: "a6-26", mainNumber: 26, priority: 5, source: "Aula 6", topic: "Herança versus Composição", prompt: "Quando a composição tende a ser melhor que herança?", options: ["Quando a relação não é uma especialização real e o objetivo é combinar comportamentos.", "Quando a classe filha é realmente um tipo da classe pai.", "Quando não existem objetos no sistema.", "Quando toda regra deve ficar duplicada.", "Quando não há atributos."], answer: 0, explanation: "O material recomenda preferir composição quando a relação 'é um' não faz sentido." },
  { id: "a6-27", mainNumber: 27, priority: 5, source: "Aula 6", topic: "Modelagem OO", prompt: "Na modelagem de sistema universitário do PDF, qual relação aparece como possibilidade correta?", options: ["Aluno participa de Turma por meio de Matrícula.", "Professor é sempre subclasse de Disciplina.", "Curso é um tipo de Aluno.", "Avaliação não pode se relacionar com Turma.", "UML impõe uma única modelagem correta."], answer: 0, explanation: "O PDF apresenta Matrícula como ligação entre Aluno e Turma." },
  { id: "a6-28", mainNumber: 28, priority: 5, source: "Aula 6", topic: "Sistemas legados", prompt: "Qual estratégia é mais segura para migrar um sistema procedural grande para POO?", options: ["Migrar de forma incremental, com mapeamento, testes e substituição gradual.", "Reescrever tudo de uma vez sem testes.", "Trocar todos os nomes de funções por métodos sem revisar responsabilidades.", "Remover regras de negócio existentes.", "Ignorar dependências globais."], answer: 0, explanation: "O PDF recomenda migração gradual e testes de caracterização." },
  { id: "a6-29", mainNumber: 29, priority: 5, source: "Aula 6", topic: "Arquitetura e Escalabilidade", prompt: "Segundo o material, POO ajuda em sistemas grandes principalmente porque:", options: ["Controla complexidade com abstração, encapsulamento, polimorfismo, coesão e baixo acoplamento.", "Resolve sozinha todos os problemas de banco e infraestrutura.", "Elimina a necessidade de testes.", "Impede modularização.", "Só serve para programas pequenos."], answer: 0, explanation: "POO ajuda, mas escalabilidade também depende de arquitetura, testes, dados e infraestrutura." },
  { id: "a6-30", mainNumber: 30, priority: 5, source: "Aula 6", topic: "Análise crítica", prompt: "Qual afirmação representa a análise crítica da arquitetura orientada a objetos?", options: ["Usar muitos conceitos avançados não garante boa arquitetura; a solução deve ser clara, coesa e proporcional.", "Quanto mais classes e interfaces, melhor automaticamente.", "Overengineering sempre melhora a legibilidade.", "SOLID obriga criar interface para tudo.", "Complexidade acidental é sempre desejável."], answer: 0, explanation: "O PDF defende usar POO de forma proporcional à necessidade real do sistema." },

  { id: "ex-01", priority: 2, source: "Aula 1", topic: "Diagrama de Classes", prompt: "Para que serve um diagrama de classes?", options: ["Planejar classes, atributos, métodos e relacionamentos antes de programar.", "Executar código Python automaticamente.", "Substituir todos os objetos por textos.", "Guardar somente imagens de personagens.", "Criar banco de dados sem classes."], answer: 0, explanation: "A Aula 1 mostra que o diagrama organiza visualmente a estrutura do sistema." },
  { id: "ex-02", priority: 2, source: "Aula 2", topic: "Classes e Objetos", prompt: "Na atividade da classe Pessoa, cada pessoa criada no código representa:", options: ["Um objeto da classe Pessoa.", "Um método da classe Pessoa.", "Uma subclasse de Pessoa.", "Um arquivo separado.", "Uma propriedade abstrata."], answer: 0, explanation: "pessoa1, pessoa2 etc. são instâncias/objetos criados a partir da classe Pessoa." },
  { id: "ex-03", priority: 2, source: "Aula 2", topic: "__init__", prompt: "No código class Carros, o método __init__ recebe marca, modelo, ano, cor, combustível e preço para:", options: ["Inicializar os atributos de cada carro.", "Imprimir automaticamente todos os carros.", "Criar herança múltipla.", "Apagar os objetos criados.", "Substituir a classe por uma função."], answer: 0, explanation: "__init__ configura os dados iniciais do objeto." },
  { id: "ex-04", priority: 3, source: "Aula 3", topic: "super()", prompt: "Nas classes Carro, Moto e Caminhao, por que o código usa super().__init__(marca, modelo, ano)?", options: ["Para reaproveitar os atributos comuns definidos em Veiculo.", "Para criar uma lista automática.", "Para impedir a criação de subclasses.", "Para fazer o programa não pedir dados.", "Para transformar números em texto."], answer: 0, explanation: "super() chama o construtor da classe principal." },
  { id: "ex-05", priority: 3, source: "Aula 3", topic: "Herança", prompt: "Na atividade de Eletrônico, Celular, Notebook e Televisao são:", options: ["Subclasses de Eletronico.", "Objetos sem classe.", "Métodos abstratos.", "Atributos da classe Produto.", "Funções globais sem relação."], answer: 0, explanation: "Elas herdam os atributos comuns de Eletronico." },
  { id: "ex-06", priority: 3, source: "Aula 4", topic: "input()", prompt: "Qual foi a principal diferença da Aula 4 em relação à Aula 3?", options: ["Os dados passaram a ser digitados pelo usuário com input().", "A herança deixou de existir.", "As classes foram substituídas por PDFs.", "Não foram usados atributos.", "O método __init__ foi removido de todas as classes."], answer: 0, explanation: "A Aula 4 usa input(), int() e float() para cadastrar dados durante a execução." },
  { id: "ex-07", priority: 3, source: "Aula 4", topic: "Conversão de tipos", prompt: "Por que o código usa int() ou float() em alguns inputs?", options: ["Para converter o texto digitado em número inteiro ou decimal.", "Para criar uma subclasse.", "Para chamar a classe principal.", "Para imprimir automaticamente.", "Para bloquear herança."], answer: 0, explanation: "input() retorna texto; int() e float() convertem para números." },
  { id: "ex-08", priority: 4, source: "Aula 5", topic: "Polimorfismo", prompt: "Na atividade dos personagens, por que existe polimorfismo?", options: ["Porque todas as subclasses têm atacar(), mas cada uma ataca de forma diferente.", "Porque nenhum personagem possui método.", "Porque Personagem não tem atributos.", "Porque todos os ataques são idênticos.", "Porque o código não usa herança."], answer: 0, explanation: "O mesmo método atacar() foi sobrescrito nas subclasses." },
  { id: "ex-09", priority: 4, source: "Aula 5", topic: "Métodos", prompt: "Na atividade de instrumentos, qual método demonstra o polimorfismo?", options: ["tocar()", "input()", "int()", "class", "self"], answer: 0, explanation: "Cada instrumento implementa tocar() com uma mensagem própria." },
  { id: "ex-10", priority: 3, source: "PPTX", topic: "self", prompt: "Segundo o material extra, o que self representa dentro de uma classe Python?", options: ["A própria instância/objeto que está executando o método.", "A classe pai obrigatória.", "Um comando para imprimir.", "Uma lista de alternativas.", "Uma forma de apagar atributos."], answer: 0, explanation: "self aponta para o objeto atual, permitindo acessar seus atributos." },
  { id: "ex-11", priority: 3, source: "PPTX", topic: "Encapsulamento", prompt: "No exemplo da classe Conta, por que usar __saldo e métodos depositar/sacar?", options: ["Para proteger o saldo e aplicar regras antes de alterar o estado.", "Para deixar o saldo sempre público.", "Para impedir consultas.", "Para evitar métodos.", "Para remover o construtor."], answer: 0, explanation: "O saldo fica protegido e só muda por operações válidas." },
  { id: "ex-12", priority: 3, source: "PPTX", topic: "Composição", prompt: "Qual exemplo representa composição do material extra?", options: ["Carro possui um Motor.", "Cachorro é um Animal.", "Pessoa é um nome.", "print possui input.", "Classe é uma planilha."], answer: 0, explanation: "Composição é relação 'possui um'; Carro possui Motor." },
  { id: "ex-13", priority: 2, source: "Aula 1", topic: "Atributos e Métodos", prompt: "No diagrama de Mortal Kombat, vida, força e velocidade são exemplos de:", options: ["Atributos.", "Métodos.", "Objetos criados.", "Bibliotecas.", "Parâmetros de CSS."], answer: 0, explanation: "Atributos são características/informações da classe." },
  { id: "ex-14", priority: 2, source: "Aula 1", topic: "Atributos e Métodos", prompt: "No diagrama de classes, atacar(), defender() e mostrarStatus() são exemplos de:", options: ["Métodos.", "Atributos.", "Objetos.", "PDFs.", "Subpastas."], answer: 0, explanation: "Métodos são ações/comportamentos que a classe pode executar." },
  { id: "ex-15", priority: 3, source: "PPTX", topic: "Coesão e Acoplamento", prompt: "O que uma arquitetura geralmente busca?", options: ["Alta coesão e baixo acoplamento.", "Baixa coesão e alto acoplamento.", "Dependência direta de tudo com tudo.", "Uma classe com todas as responsabilidades.", "Nenhum relacionamento entre objetos."], answer: 0, explanation: "Alta coesão e baixo acoplamento facilitam manutenção e evolução." }
];

const HARDER_QUESTIONS = {
  "a6-01": { difficulty: "Média", answer: 2, remember: "POO organiza dados e comportamentos próximos dentro de objetos.", options: ["Organizar o programa em funções independentes que recebem estruturas de dados como parâmetro.", "Separar todos os atributos em arquivos próprios e deixar os métodos fora das entidades.", "Organizar o software em objetos que reúnem estado, atributos e comportamentos relacionados.", "Usar classes apenas como nomes para grupos de funções sem representar entidades.", "Criar hierarquias de herança para qualquer parte do sistema, mesmo sem relação real."] },
  "a6-02": { difficulty: "Fácil", answer: 3, remember: "Classe é modelo; objeto é instância concreta desse modelo.", options: ["Classe é o valor guardado em memória; objeto é o comando usado para imprimir esse valor.", "Classe é uma instância com dados próprios; objeto é o molde que define atributos e métodos.", "Classe e objeto são termos equivalentes quando o código usa __init__().", "Classe é o modelo que define estrutura e comportamento; objeto é uma instância criada a partir dela.", "Objeto é sempre uma subclasse, enquanto classe é sempre a classe-pai."] },
  "a6-03": { difficulty: "Média", answer: 1, remember: "Abstração seleciona o essencial para o contexto do sistema.", options: ["Copiar para o sistema todas as características reais de uma entidade para evitar perda de informação.", "Representar apenas os aspectos relevantes de uma entidade para resolver o problema daquele contexto.", "Esconder todos os métodos da classe para que nenhum objeto consiga executar comportamentos.", "Transformar atributos em métodos para reduzir a quantidade de dados no objeto.", "Criar subclasses para cada detalhe de uma entidade, mesmo quando o sistema não precisa deles."] },
  "a6-04": { difficulty: "Média", answer: 4, remember: "Encapsulamento protege o estado interno e centraliza regras na classe.", options: ["Dividir a classe em várias subclasses para reduzir o tamanho do arquivo.", "Permitir que qualquer parte do sistema altere diretamente todos os atributos.", "Usar herança para copiar métodos de uma classe para outra.", "Trocar atributos por variáveis globais acessíveis por qualquer função.", "Reunir dados e comportamentos em uma classe, controlando como o estado é acessado e alterado."] },
  "a6-05": { difficulty: "Média", answer: 0, remember: "Regras de negócio devem ficar nos métodos responsáveis pelo estado.", options: ["Porque permite ignorar validações como saldo suficiente, valor positivo e registro correto da operação.", "Porque atributos numéricos em Python só podem ser alterados dentro de classes abstratas.", "Porque o saldo deveria ser calculado apenas no momento do print(), não guardado no objeto.", "Porque métodos como sacar() e depositar() não conseguem alterar atributos privados.", "Porque encapsulamento exige que todo atributo de uma conta seja público e editável."] },
  "a6-06": { difficulty: "Fácil", answer: 1, remember: "Herança representa uma relação de especialização e reutilização.", options: ["Criar objetos iguais, obrigando todos a terem os mesmos valores nos atributos.", "Criar uma classe baseada em outra, reutilizando atributos e métodos comuns.", "Executar automaticamente todos os métodos da classe-pai ao declarar uma subclasse.", "Copiar uma classe para outra sem existir relação entre os conceitos.", "Transformar um método herdado em atributo público da subclasse."] },
  "a6-07": { difficulty: "Média", answer: 3, remember: "Polimorfismo: mesma operação, comportamentos específicos.", options: ["Quando uma subclasse recebe os atributos da classe-pai usando super().__init__().", "Quando um objeto protege seus dados usando atributos com underline.", "Quando uma classe define muitos métodos com nomes diferentes.", "Quando objetos diferentes respondem à mesma chamada de método de formas diferentes.", "Quando um método possui parâmetros opcionais para simular sobrecarga."] },
  "a6-08": { difficulty: "Difícil", answer: 2, remember: "Polimorfismo permite estender comportamentos sem mexer no fluxo principal.", options: ["Porque todas as classes de pagamento passam a guardar os mesmos atributos internos.", "Porque o código principal passa a conhecer todos os detalhes de Cartao, Pix e Boleto.", "Porque novas formas de pagamento podem implementar a mesma operação sem alterar o processamento principal.", "Porque elimina a necessidade de criar subclasses ou abstrações para formas de pagamento.", "Porque obriga que todas as formas de pagamento executem exatamente o mesmo código."] },
  "a6-09": { difficulty: "Média", answer: 4, remember: "Sobrescrita redefine na subclasse um método herdado.", options: ["Criar um método com mesmo nome e parâmetros diferentes na mesma classe.", "Chamar super().__init__() para reaproveitar atributos da classe-pai.", "Criar vários objetos de uma mesma classe com valores diferentes.", "Definir um atributo com dois underlines para evitar acesso direto simples.", "Redefinir em uma subclasse um método que já existia na classe principal."] },
  "a6-10": { difficulty: "Média", answer: 1, remember: "Composição representa relação 'possui/é formado por'.", options: ["Uma classe filha troca completamente o comportamento da classe-pai.", "Um objeto é formado por outros objetos que fazem parte de sua estrutura.", "Um método recebe diferentes quantidades de parâmetros.", "Uma classe acessa diretamente atributos privados de outra classe.", "Uma subclasse é usada onde uma superclasse era esperada."] },
  "a6-11": { difficulty: "Fácil", answer: 0, remember: "__init__ inicializa a instância com seus valores iniciais.", options: ["Inicializar o objeto quando ele é criado, geralmente guardando valores nos atributos.", "Definir o texto exibido quando print(objeto) é chamado.", "Comparar dois objetos quando usamos o operador ==.", "Criar automaticamente uma subclasse com os mesmos métodos.", "Indicar ao Python a ordem de busca em herança múltipla."] },
  "a6-12": { difficulty: "Média", answer: 2, remember: "Em Python, encapsulamento é fortemente baseado em convenções.", options: ["Por regras rígidas que tornam impossível acessar qualquer atributo fora da classe.", "Somente por classes abstratas criadas com o módulo abc.", "Por convenções como _atributo, name mangling com __atributo, propriedades e bom design.", "Pelo uso obrigatório de getters e setters para todos os atributos públicos.", "Pela proibição de métodos que alterem o estado interno do objeto."] },
  "a6-13": { difficulty: "Média", answer: 4, remember: "super().__init__ reaproveita a inicialização da classe-pai.", options: ["Criar uma nova classe-pai durante a execução do programa.", "Transformar os atributos da subclasse em variáveis globais.", "Executar todos os métodos da classe-pai em ordem alfabética.", "Impedir que a subclasse sobrescreva métodos herdados.", "Chamar o construtor da superclasse para inicializar a parte comum do objeto."] },
  "a6-14": { difficulty: "Difícil", answer: 1, remember: "Duck typing foca no comportamento disponível, não no tipo declarado.", options: ["Um objeto só pode ser usado se herdar explicitamente da classe esperada.", "Se o objeto possui os métodos necessários, ele pode ser usado mesmo sem herança formal.", "Toda subclasse precisa implementar métodos abstratos definidos por abc.", "O Python escolhe automaticamente entre métodos sobrecarregados pelo tipo dos argumentos.", "A classe-pai sempre decide qual método da subclasse será chamado."] },
  "a6-15": { difficulty: "Média", answer: 3, remember: "Dunder methods integram objetos às operações nativas da linguagem.", options: ["Métodos criados apenas para esconder atributos privados de uma classe.", "Funções externas usadas para converter input() em int() ou float().", "Métodos que só podem existir dentro de classes abstratas.", "Métodos cercados por dois sublinhados que definem comportamentos como str(), len() e ==", "Métodos sobrescritos que obrigatoriamente chamam super()."] },
  "a6-16": { difficulty: "Média", answer: 0, remember: "Classe abstrata define contrato para subclasses.", options: ["Definir uma abstração/contrato com operações que as subclasses devem implementar.", "Criar objetos concretos automaticamente sem precisar de subclasses.", "Substituir herança por composição em todos os casos.", "Permitir que atributos públicos sejam acessados como privados.", "Resolver automaticamente conflitos de múltipla herança."] },
  "a6-17": { difficulty: "Difícil", answer: 4, remember: "Múltipla herança pode gerar conflitos; o MRO define a ordem de busca.", options: ["Ela impede qualquer classe de sobrescrever métodos herdados.", "Ela torna obrigatório usar property em todos os atributos.", "Ela elimina a necessidade de composição entre objetos.", "Ela transforma métodos de instância em métodos estáticos.", "Ela pode aumentar a complexidade e gerar conflitos, como no problema do diamante."] },
  "a6-18": { difficulty: "Difícil", answer: 2, remember: "property permite validar acesso mantendo sintaxe simples.", options: ["Criar uma subclasse sem precisar declarar class.", "Forçar o Python a escolher um método sobrecarregado pelo tipo.", "Permitir acessar um atributo com sintaxe simples, mas mantendo validação e controle.", "Ocultar completamente um atributo, tornando impossível consultá-lo.", "Substituir o método __init__ por uma variável pública."] },
  "a6-19": { difficulty: "Média", answer: 1, remember: "Pedido possui itens; ItemPedido não é um tipo de Pedido.", options: ["Porque ItemPedido deve sobrescrever todos os métodos de Pedido.", "Porque um Pedido é formado por itens; ItemPedido não representa uma especialização de Pedido.", "Porque Produto precisa herdar de Cliente para calcular o total.", "Porque composição só pode existir quando não há métodos.", "Porque herança é sempre proibida em sistemas de comércio eletrônico."] },
  "a6-20": { difficulty: "Difícil", answer: 3, remember: "Strategy encapsula variações de algoritmo atrás de uma interface comum.", options: ["Substituir qualquer método herdado por uma função global.", "Guardar todas as estratégias dentro de uma única sequência de if/else.", "Criar uma hierarquia apenas para reaproveitar atributos sem comportamento.", "Encapsular algoritmos intercambiáveis atrás de um contrato usado pelo contexto.", "Impedir que o contexto receba objetos de classes diferentes."] },
  "a6-21": { difficulty: "Média", answer: 0, remember: "SRP trata responsabilidade e motivo para mudar, não quantidade de métodos.", options: ["Uma classe deve ter responsabilidade bem definida e motivos de mudança coerentes.", "Uma classe deve sempre possuir exatamente um método público.", "Uma classe deve concentrar cadastro, validação, desconto, relatório e e-mail para ficar completa.", "Uma classe só respeita SRP quando não possui atributos.", "Uma classe deve depender diretamente das implementações que utiliza."] },
  "a6-22": { difficulty: "Média", answer: 4, remember: "OCP busca extensão sem alteração constante do código existente.", options: ["Toda regra nova deve ser adicionada editando a mesma função central.", "Uma classe deve ser fechada para receber novas funcionalidades.", "A única forma de aplicar OCP é usar herança múltipla.", "O código principal deve conhecer todas as implementações concretas.", "O sistema deve permitir extensão, evitando modificar repetidamente partes já existentes."] },
  "a6-23": { difficulty: "Fácil", answer: 2, remember: "Baixo acoplamento reduz impacto; alta coesão agrupa responsabilidades relacionadas.", options: ["Alto acoplamento e alta fragmentação de responsabilidades.", "Baixo acoplamento e baixa coesão entre métodos da mesma classe.", "Baixo acoplamento e alta coesão.", "Dependência direta entre todas as classes para facilitar chamadas.", "Uma única classe concentrando banco, e-mail, pagamento e relatório."] },
  "a6-24": { difficulty: "Média", answer: 1, remember: "Interface mostra o que usar; implementação guarda como funciona.", options: ["Para impedir que classes diferentes compartilhem o mesmo nome de método.", "Para permitir usar um comportamento sem depender dos detalhes internos da implementação.", "Para garantir que todo atributo seja público.", "Para substituir composição por herança em todas as relações.", "Para fazer o código consumidor depender de um banco específico."] },
  "a6-25": { difficulty: "Difícil", answer: 3, remember: "DIP recomenda depender de abstrações, não detalhes concretos.", options: ["Classes centrais devem depender diretamente de MySQL para evitar camadas extras.", "Subclasses devem depender sempre dos atributos privados da superclasse.", "Métodos devem receber apenas tipos primitivos, nunca objetos.", "Classes importantes devem depender de abstrações, permitindo trocar implementações.", "Interfaces devem depender de classes concretas para facilitar manutenção."] },
  "a6-26": { difficulty: "Difícil", answer: 0, remember: "Composição é melhor quando a relação é 'possui' ou combina comportamentos.", options: ["Quando não existe uma relação real de especialização e o objetivo é combinar comportamentos.", "Quando uma subclasse respeita totalmente o contrato da superclasse.", "Quando a classe filha é claramente um tipo da classe-pai.", "Quando o método herdado precisa ser chamado por super().__init__().", "Quando o sistema exige polimorfismo por substituição obrigatoriamente."] },
  "a6-27": { difficulty: "Média", answer: 4, remember: "Modelagem depende do domínio; Matrícula liga Aluno e Turma.", options: ["Curso deve obrigatoriamente herdar de Disciplina para compartilhar carga horária.", "Professor deve ser modelado como atributo simples de Aluno.", "UML sempre impõe uma única modelagem correta para o domínio.", "Avaliação não pode ser parte de Turma porque composição é proibida em UML.", "Aluno pode participar de Turma por meio de Matrícula, dependendo das regras do domínio."] },
  "a6-28": { difficulty: "Média", answer: 2, remember: "Migração segura é incremental e sustentada por testes.", options: ["Reescrever todo o sistema de uma vez para eliminar código procedural rapidamente.", "Trocar nomes de funções por métodos sem reorganizar responsabilidades.", "Migrar gradualmente, mapeando dependências, criando testes e substituindo partes aos poucos.", "Remover variáveis globais antes de entender as regras de negócio que dependem delas.", "Criar classes para todas as funções antigas, mantendo o mesmo acoplamento."] },
  "a6-29": { difficulty: "Difícil", answer: 1, remember: "POO ajuda a controlar complexidade, mas não resolve tudo sozinha.", options: ["POO garante automaticamente escalabilidade arquitetural se houver muitas interfaces.", "POO contribui com abstração, encapsulamento, polimorfismo, coesão e baixo acoplamento.", "POO elimina a necessidade de testes, observabilidade e arquitetura de módulos.", "POO torna banco de dados e infraestrutura irrelevantes para sistemas grandes.", "POO só escala quando todas as classes usam múltipla herança."] },
  "a6-30": { difficulty: "Difícil", answer: 3, remember: "Boa arquitetura usa POO de forma proporcional, clara e justificável.", options: ["Uma arquitetura é melhor quanto mais padrões e interfaces ela possui.", "Overengineering reduz sempre a complexidade do domínio.", "SOLID deve ser seguido criando classes para tudo, mesmo sem necessidade.", "Conceitos avançados não garantem qualidade; clareza, coesão e simplicidade também importam.", "Complexidade acidental é aceitável quando há muitas abstrações."] },
  "ex-01": { difficulty: "Fácil", answer: 1, remember: "Diagrama de classes planeja estrutura antes do código.", options: ["Executar métodos Python sem precisar criar objetos.", "Representar classes, atributos, métodos e relacionamentos do sistema.", "Guardar objetos reais já instanciados durante o programa.", "Substituir a criação de classes por imagens no código.", "Definir o gabarito de alternativas de uma prova."] },
  "ex-02": { difficulty: "Fácil", answer: 3, remember: "pessoa1 é objeto; Pessoa é classe.", options: ["Uma subclasse criada automaticamente pela chamada Pessoa(...).", "Um método chamado dentro de __init__.", "Um atributo compartilhado por todas as pessoas.", "Um objeto/instância da classe Pessoa.", "Uma classe abstrata sem implementação."] },
  "ex-03": { difficulty: "Média", answer: 0, remember: "__init__ guarda os dados iniciais do objeto.", options: ["Receber os valores e inicializar os atributos de cada objeto Carros.", "Executar os prints de todos os carros cadastrados.", "Transformar a classe Carros em subclasse de Veiculo.", "Definir qual alternativa do simulado será correta.", "Criar automaticamente dez objetos diferentes."] },
  "ex-04": { difficulty: "Média", answer: 2, remember: "super chama a parte comum da classe-pai.", options: ["Para executar o método apresentar() de todas as subclasses.", "Para converter marca, modelo e ano em valores digitados por input().", "Para inicializar marca, modelo e ano usando o construtor de Veiculo.", "Para criar polimorfismo entre Carro, Moto e Caminhao.", "Para impedir que a subclasse tenha atributos específicos."] },
  "ex-05": { difficulty: "Fácil", answer: 4, remember: "Subclasse herda atributos comuns e adiciona específicos.", options: ["Objetos criados dentro da classe Produto.", "Métodos sobrescritos sem relação com Eletronico.", "Atributos públicos da classe principal.", "Classes abstratas obrigatórias.", "Subclasses que herdam de Eletronico."] },
  "ex-06": { difficulty: "Fácil", answer: 1, remember: "input() recebe dados durante a execução.", options: ["As subclasses deixaram de chamar super().__init__().", "Os dados passaram a ser informados pelo usuário com input().", "A herança foi substituída por composição em todos os exemplos.", "Os objetos passaram a ser criados sem construtor.", "Os métodos deixaram de exibir informações na tela."] },
  "ex-07": { difficulty: "Média", answer: 3, remember: "input() retorna texto; converta para número quando necessário.", options: ["Para indicar que o atributo pertence à classe-pai.", "Para fazer o método apresentar() funcionar com polimorfismo.", "Para esconder atributos usando encapsulamento.", "Para transformar o texto digitado pelo usuário em número inteiro ou decimal.", "Para declarar uma classe abstrata."] },
  "ex-08": { difficulty: "Média", answer: 0, remember: "Polimorfismo aparece quando atacar() muda por subclasse.", options: ["Porque Guerreiro, Mago, Arqueiro, Ninja e Assassino redefinem atacar() com comportamentos diferentes.", "Porque todos os personagens possuem exatamente os mesmos atributos específicos.", "Porque Personagem não possui métodos próprios.", "Porque o código usa input() para receber os dados.", "Porque os personagens não herdam de nenhuma classe principal."] },
  "ex-09": { difficulty: "Média", answer: 2, remember: "tocar() é sobrescrito nos instrumentos.", options: ["apresentar()", "__init__()", "tocar()", "input()", "int()"] },
  "ex-10": { difficulty: "Média", answer: 4, remember: "self referencia a instância atual.", options: ["A classe-pai que será chamada por super().", "Um parâmetro usado apenas em classes abstratas.", "O nome do arquivo onde a classe foi criada.", "Uma variável global compartilhada por todos os objetos.", "A própria instância que executa o método e acessa seus atributos."] },
  "ex-11": { difficulty: "Média", answer: 1, remember: "Encapsular saldo evita alterações inválidas.", options: ["Para impedir completamente qualquer consulta ao saldo.", "Para proteger o saldo e obrigar alterações por regras de depositar() e sacar().", "Para transformar saldo em método especial __saldo__.", "Para fazer a classe Conta herdar de Banco.", "Para permitir que qualquer código externo altere saldo diretamente."] },
  "ex-12": { difficulty: "Fácil", answer: 3, remember: "Composição é relação 'possui um'.", options: ["Cachorro é um Animal.", "Professor herda de Funcionario.", "Gato sobrescreve emitir_som().", "Carro possui um Motor.", "Produto inicializa nome e preço."] },
  "ex-13": { difficulty: "Fácil", answer: 0, remember: "Atributos são características da classe/objeto.", options: ["Atributos.", "Métodos.", "Subclasses.", "Construtores.", "Associações."] },
  "ex-14": { difficulty: "Fácil", answer: 2, remember: "Métodos são comportamentos ou ações.", options: ["Atributos.", "Objetos.", "Métodos.", "Pacotes.", "Instâncias."] },
  "ex-15": { difficulty: "Média", answer: 4, remember: "Boa arquitetura busca dependências menores e responsabilidades relacionadas.", options: ["Alto acoplamento e baixa coesão para centralizar alterações.", "Classes muito pequenas, mesmo sem significado claro.", "Dependência direta de banco, e-mail e pagamento na mesma classe.", "Herança em todas as relações para evitar composição.", "Baixo acoplamento e alta coesão."] }
};

const CHALLENGE_QUESTIONS = [
  { id: "ch-01", priority: 4, source: "Desafio", topic: "Polimorfismo", difficulty: "Difícil", challenge: true, prompt: "Considere:\n\nclass Animal:\n    def emitir_som(self):\n        print('Som')\nclass Cachorro(Animal):\n    def emitir_som(self):\n        print('Au au')\nclass Gato(Animal):\n    def emitir_som(self):\n        print('Miau')\n\nfor animal in [Cachorro(), Gato()]:\n    animal.emitir_som()\n\nQual conceito aparece na execução?", options: ["Encapsulamento, porque os atributos estão protegidos.", "Polimorfismo, porque o mesmo método produz comportamentos diferentes.", "Composição, porque Cachorro possui um Animal.", "Sobrecarga, porque Python escolhe pelo tipo do parâmetro.", "Abstração, porque os objetos não possuem estado."], answer: 1, explanation: "A chamada emitir_som() é a mesma, mas cada objeto executa sua versão.", remember: "Polimorfismo = mesma operação, respostas diferentes." },
  { id: "ch-02", priority: 4, source: "Desafio", topic: "super()", difficulty: "Difícil", challenge: true, prompt: "No código:\n\nclass Pessoa:\n    def __init__(self, nome):\n        self.nome = nome\nclass Aluno(Pessoa):\n    def __init__(self, nome, matricula):\n        super().__init__(nome)\n        self.matricula = matricula\n\nO que super().__init__(nome) faz?", options: ["Cria outro objeto Aluno dentro da classe Pessoa.", "Chama o construtor de Pessoa para inicializar o atributo comum nome.", "Sobrescreve o método __init__ de Pessoa permanentemente.", "Transforma matricula em atributo protegido.", "Executa todos os métodos da classe Pessoa."], answer: 1, explanation: "super().__init__(nome) reaproveita a inicialização da classe-pai.", remember: "Use super() para chamar a implementação da superclasse." },
  { id: "ch-03", priority: 4, source: "Desafio", topic: "Encapsulamento", difficulty: "Difícil", challenge: true, prompt: "Uma classe Conta permite conta.saldo = -5000 em qualquer parte do sistema. Qual problema de POO isso indica?", options: ["Falta de polimorfismo, pois saldo deveria ser método sobrescrito.", "Falta de encapsulamento, pois o estado pode ser alterado sem regra de negócio.", "Uso incorreto de herança, pois Conta deveria herdar de Saldo.", "Excesso de abstração, pois saldo é uma entidade real.", "Aplicação correta de composição, pois saldo faz parte da conta."], answer: 1, explanation: "O saldo deveria ser protegido e alterado por métodos como sacar/depositar.", remember: "Encapsulamento protege invariantes e regras do objeto." },
  { id: "ch-04", priority: 4, source: "Desafio", topic: "Herança versus Composição", difficulty: "Difícil", challenge: true, prompt: "Você está modelando Carro e Motor. Qual modelagem é mais coerente com o material?", options: ["class Motor(Carro), pois motor é um tipo de carro.", "class Carro(Motor), pois carro deve herdar os métodos do motor.", "class Carro: self.motor = Motor(), pois carro possui motor.", "class Motor: self.carro = Carro(), pois todo motor controla o carro inteiro.", "Usar herança múltipla para Carro herdar de Motor e Combustivel sempre."], answer: 2, explanation: "A relação correta é 'Carro possui Motor', então composição representa melhor.", remember: "Herança é 'é um'; composição é 'possui um'." },
  { id: "ch-05", priority: 4, source: "Desafio", topic: "__init__", difficulty: "Média", challenge: true, prompt: "No código:\n\nclass Produto:\n    def __init__(self, nome, preco):\n        self.nome = nome\n        self.preco = preco\n\np = Produto('Notebook', 3000)\n\nApós a execução, o que p.nome representa?", options: ["O método construtor da classe Produto.", "Um atributo do objeto p com valor 'Notebook'.", "Uma variável local que deixa de existir após __init__.", "Uma subclasse de Produto chamada Notebook.", "Um método especial de comparação."], answer: 1, explanation: "self.nome guarda no objeto p o valor recebido no construtor.", remember: "Atributos do objeto ficam em self." },
  { id: "ch-06", priority: 4, source: "Desafio", topic: "Sobrescrita", difficulty: "Média", challenge: true, prompt: "Uma classe Professor herda de Funcionario e define novamente o método apresentar(). O que aconteceu?", options: ["Sobrescrita de método herdado.", "Sobrecarga automática por tipo de parâmetro.", "Composição entre Professor e Funcionario.", "Name mangling do método apresentar.", "Criação de uma propriedade somente leitura."], answer: 0, explanation: "A subclasse redefiniu um método que já existia na classe-pai.", remember: "Sobrescrita = redefinir método herdado." },
  { id: "ch-07", priority: 4, source: "Desafio", topic: "OCP", difficulty: "Difícil", challenge: true, prompt: "Uma função processar_pagamento possui vários ifs para Cartão, Pix e Boleto. Toda nova forma de pagamento exige editar essa função. Qual princípio/conceito ajuda a melhorar esse cenário?", options: ["SRP apenas, mantendo todos os ifs em uma classe menor.", "Polimorfismo/OCP, criando implementações com o mesmo método processar().", "Múltipla herança obrigatória entre Cartão, Pix e Boleto.", "Encapsulamento por atributo público forma_pagamento.", "Duck typing proibindo novas classes de pagamento."], answer: 1, explanation: "Com polimorfismo, cada pagamento implementa processar() e o fluxo principal muda menos.", remember: "OCP: estender sem modificar continuamente o código existente." },
  { id: "ch-08", priority: 4, source: "Desafio", topic: "self", difficulty: "Média", challenge: true, prompt: "Qual alternativa corrige melhor este método?\n\nclass Pessoa:\n    def apresentar():\n        print(self.nome)", options: ["def apresentar(self):\n    print(self.nome)", "def apresentar(nome):\n    print(self.nome)", "def apresentar():\n    print(nome.self)", "def apresentar(super):\n    print(super.nome)", "def apresentar(__init__):\n    print(self.nome)"], answer: 0, explanation: "Método de instância precisa receber self para acessar atributos do objeto.", remember: "self deve aparecer como parâmetro do método de instância." },
  { id: "ch-09", priority: 4, source: "Desafio", topic: "Property", difficulty: "Difícil", challenge: true, prompt: "Por que usar @property para idade em uma classe Pessoa?", options: ["Para transformar idade em classe abstrata.", "Para permitir validar valores antes de alterar idade, mantendo acesso simples.", "Para obrigar idade a ser sempre pública sem validação.", "Para fazer idade herdar de Pessoa.", "Para executar automaticamente todos os métodos da classe."], answer: 1, explanation: "@property permite controlar leitura/escrita e validar valores como idade negativa.", remember: "property ajuda no encapsulamento sem perder sintaxe simples." },
  { id: "ch-10", priority: 4, source: "Desafio", topic: "Acoplamento e Coesão", difficulty: "Difícil", challenge: true, prompt: "Uma classe Pedido salva no banco, envia e-mail, calcula pagamento e gera relatório. Qual crítica do material se aplica melhor?", options: ["A classe tem alta coesão porque faz muitas tarefas importantes.", "A classe mistura responsabilidades e tende a ter alto acoplamento.", "A classe aplica corretamente SRP porque tudo envolve Pedido.", "A classe deveria usar mais herança em vez de separar serviços.", "A classe é exemplo de baixo acoplamento por acessar vários componentes diretamente."], answer: 1, explanation: "O material recomenda separar responsabilidades e reduzir dependências diretas.", remember: "Alta coesão = responsabilidades relacionadas; baixo acoplamento = poucas dependências diretas." }
];

Object.entries(HARDER_QUESTIONS).forEach(([id, patch]) => {
  const question = QUESTION_BANK.find(item => item.id === id);
  if (question) Object.assign(question, patch);
});

QUESTION_BANK.push(...CHALLENGE_QUESTIONS);

if (typeof window !== "undefined") window.QUESTION_BANK = QUESTION_BANK;

const QUICK_REVIEW = [
  { topic: "Classes", definition: "Classe é o modelo usado para criar objetos.", example: "class Pessoa define quais dados e ações uma pessoa terá.", remember: "Classe é molde; objeto é instância." },
  { topic: "Objetos", definition: "Objeto é algo criado a partir de uma classe, com seus próprios valores.", example: "pessoa1 = Pessoa('João', 25).", remember: "Dois objetos podem vir da mesma classe e ter valores diferentes." },
  { topic: "__init__()", definition: "Método construtor que prepara o objeto quando ele é criado.", example: "def __init__(self, nome): self.nome = nome.", remember: "Use para receber e guardar os atributos iniciais." },
  { topic: "self", definition: "Representa o próprio objeto que está executando o método.", example: "self.nome guarda o nome daquele objeto específico.", remember: "Sem self, o método não acessa corretamente os atributos do objeto." },
  { topic: "Herança", definition: "Permite criar uma classe baseada em outra.", example: "class Cachorro(Animal): herda dados e comportamentos de Animal.", remember: "Use quando existe relação verdadeira de especialização: 'é um'." },
  { topic: "super()", definition: "Chama métodos da classe principal, geralmente o construtor.", example: "super().__init__(nome) reaproveita a inicialização da classe pai.", remember: "Evita repetir atributos comuns nas subclasses." },
  { topic: "Polimorfismo", definition: "Mesmo método, comportamentos diferentes em classes diferentes.", example: "Cachorro.emitir_som() e Gato.emitir_som() respondem diferente.", remember: "Nas aulas, atacar() e tocar() demonstraram polimorfismo." },
  { topic: "Encapsulamento", definition: "Controla o acesso ao estado interno do objeto.", example: "Conta usa __saldo e métodos depositar(), sacar().", remember: "Protege regras de negócio contra alterações inválidas." },
  { topic: "Abstração", definition: "Escolhe somente os aspectos importantes para o sistema.", example: "Pessoa em sistema universitário precisa matrícula; em hospital precisa tipo sanguíneo.", remember: "Abstrair é reduzir complexidade." },
  { topic: "Composição", definition: "Um objeto possui outro objeto como parte.", example: "Pedido possui ItemPedido; Carro possui Motor.", remember: "Use composição quando a relação é 'possui um', não 'é um'." },
  { topic: "input(), int(), float()", definition: "input recebe texto; int e float convertem para número.", example: "idade = int(input('Digite a idade: ')).", remember: "Converta quando precisar calcular ou guardar número." },
  { topic: "SOLID", definition: "Conjunto de princípios para organizar responsabilidades e dependências.", example: "SRP separa cadastro, validação, relatório e e-mail em classes diferentes.", remember: "Não é para criar complexidade sem necessidade." }
];

if (typeof window !== "undefined") window.QUICK_REVIEW = QUICK_REVIEW;
